### ISSUE TITLE
Definition of variables (SSID, password, senseBox ID)

### ISSUE THREAD

**Issue by johnjohndoe** [sensebox/senseBox-bike-Arduino#2]
The README.md states:

> In der Datei `variables/network.h` WiFi Informationen (SSID und Passwort) eingeben
> In der Datei `variables/ids.h` senseBox ID und Sensor ID's von der openSenseMap eintragen

Can you please document which **variable names** must be used and in which **format the variables assignment** must be declared? Comments with examples in the relevant files should be sufficient.

**Comment by Thiemann96** [comment]
Thanks for the help!  You think this is clear enough ?

**Comment by johnjohndoe** [comment]
Yes, 7322b8832bf9d0833ff8602e8c9a8cc87f2907c4 and c8c4b345e998107f3c212b2907e84cc16b7fc68e look great. Thanks.
