### ISSUE TITLE
Additional library needed on (arch) linux

### ISSUE THREAD

**Issue by goetzvr** [sensebox/senseBox-bike-Arduino#4]
https://github.com/sensebox/senseBox-bike-Arduino/blob/ba2977e16af43f080c803c904fdd1dc789f8fbd9/README.md?plain=1#L11

On arch-linux with the arduino-git  IDE package I had to additionally install the SD-library to get it compiled.

` arduino-cli lib install SD`

**Comment by johnjohndoe** [comment]
@goetzvr You documented this in 25d56fe5e9c4c3b221c5a7ce093b88702c05abb1 which is meanwhile merged into `main`. I think this issue can be closed.
